name: SonarQube Scan

on:
  push:
    branches:
      - main  # Modifier si nécessaire
  pull_request:
    branches:
      - main  # Modifier si nécessaire

jobs:
  build_test_and_scan:
    name: Build, Test, and SonarQube Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Modifier si nécessaire

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Run tests
        run: |
          # Exécuter ici vos commandes de tests, par exemple :
          # npm install
          # npm test

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          projectBaseDir: ./  # Modifier si nécessaire
          token: ${{ secrets.SONARQUBE_TOKEN }}
