name: SonarQube Scan

on:
  push:
    branches:
      - main  # Modifier si nécessaire
  pull_request:
    branches:
      - main  # Modifier si nécessaire

jobs:
  build_test_and_scan:
    name: Build, Test, and SonarQube Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '17'
    
      - name: Build
        uses: actions/setup-java@v2
        with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '17'
         script:
              -chmod +x ./mvnw 
             -./mvnw package -Dmaven.test.skip=true
              -./mvnw compile
             -Dmaven.test.skip=true
             -Dhttps.protocols=TLSv1.2
             -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
             -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
             -Dorg.slf4j.simpleLogger.showDateTime=true
             -Djava.awt.headless=true
             --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true

      - name: Build Docker image
        run: |
          pwd
          ls
          docker build -t myapp /docker
        
      - name: Run tests on Docker image
        run: |
          docker run myapp mvn clean test

      - name: Jenkins Integration
        run: |
          # Remplacez les valeurs ci-dessous par les informations de votre serveur Jenkins
          export JENKINS_URL=<URL_DE_VOTRE_SERVEUR_JENKINS>
          export JENKINS_USER=<VOTRE_NOM_D_UTILISATEUR>
          export JENKINS_TOKEN=<VOTRE_TOKEN>
          
          # Exemple de commande pour déclencher un build dans Jenkins
          curl -X POST -u $JENKINS_USER:$JENKINS_TOKEN $JENKINS_URL/job/NOM_DU_JOB/build
          
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ./  # Modifier si nécessaire
          token: ${{ secrets.SONARQUBE_TOKEN }}
